### ISSUE TITLE
Fix dialog box always only opening last flower on a bed page

### ISSUE THREAD

**Issue by danfrz** [UMM-CSci-3601-S17/digital-display-garden-iteration-2-grimaldi#12]
@danfrz commented on [Tue Mar 21 2017](https://github.com/UMM-CSci-3601-S17/digital-display-garden-iteration-1-heatmappers/issues/14)

---

@danfrz commented on [Tue Mar 21 2017](https://github.com/UMM-CSci-3601-S17/digital-display-garden-iteration-1-heatmappers/issues/14#issuecomment-288216871)

WRONG REPO

**Comment by lverns** [comment]
@carav008 said that this issue was created by accident and has been resolved.
