### ISSUE TITLE
Add "Contact Us" to a footer on every page

### ISSUE THREAD

**Issue by danfrz** [UMM-CSci-3601-S17/digital-display-garden-iteration-2-grimaldi#13]

**Comment by danfrz** [comment]
Added because Nic mentioned it on Slack

**Comment by ferri082** [comment]
There is an issue putting a footer on the bed pages because they are listing flowers. When we add the flowers as a scroll box and have the comment box, then the footer is able to be displayed on those pages. Otherwise the code on this branch looks like it can be merged.
