### ISSUE TITLE
Display counts of comments on visitor website

### ISSUE THREAD

**Issue by lverns** [UMM-CSci-3601-S17/digital-display-garden-iteration-2-grimaldi#4]
- [ ] create method for getting counts from the DB
- [ ] create API endpoint
- [ ] client-side stuff

**Comment by danfrz** [comment]
Pull request #22 Closes this

**Comment by danfrz** [comment]
My bad, we haven't cherrypicked the comment fix from #1

**Comment by danfrz** [comment]
Comment counts now work, cherrypick'd change to comments made in feedback-export branch

**Comment by lverns** [comment]
What branch has the code where comment counts work?

**Comment by lverns** [comment]
Oh nevermind, it's on master.
