### ISSUE TITLE
Track the number of times a flower page is visited

### ISSUE THREAD

**Issue by lverns** [UMM-CSci-3601-S17/digital-display-garden-iteration-2-grimaldi#8]

**Comment by lverns** [comment]
The data is being put in the database, but we haven't yet implemented the ability to export or view that info, so we should leave this issue open for now.

**Comment by NicMcPhee** [comment]
@lverns said to leave it open, and then @danfrz closed it with no comment and with no attached commits. What actually happened here?

**Comment by ferri082** [comment]
@NicMcPhee From my understanding, the issue was closed because it was initially made to just track the flowers and have a timestamp available. Which was accomplished. @dabfrz and I did not see the comment on the issue and thought it just wasn't moved to closed yet.

**Comment by danfrz** [comment]
@nicmcphee @ferri082 @lverns Woops! I did read the comment at an earlier time when it was made, but at the end we were evaluating what stories we did again and totally forgot about the comment.
